blank_issues_enabled: true
contact_links:
  - name: Setup help and community discussion
    url: https://discord.playgenerals.online
    about: Ask usage questions and discuss mods with the GeneralsOnline community.
